batch_size: 16
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202501201958
train_epochs: 100
train_workers: 20
vocab: :X'M;Z0mG68!Wrfqt,DYS7V/AK*aFPNo 2#kgbR.h+p(LB)"IeHQ9xv&lsUO3ynwc?iTJ5zd-4Ej1uC
width: 1408
